### ISSUE TITLE
Wrapper only characterized at one corner

### ISSUE THREAD

**Issue by donn** [efabless/EF_SRAM_1024x32#11]
The wrapper is only characterized at a single corner, tt/25°C/1.8V.

The standard cell library for sky130 is also characterized at ss/100°C/1.6V and tt/-25°C /1.95V.

**Comment by donn** [comment]
Investigating further, it appears that the wrapper's liberty file is basically just the macro's liberty files with a couple renames:

```diff
$ diff lib/EF_SRAM_1024x32_tt_180V_25C.lib lib/EF_SRAM_1024x32_wrapper_tt_180V_25C.lib
29c29
< library (EF_SRAM_1024x32_tt_180V_25C) {
---
> library (EF_SRAM_1024x32_wrapper_tt_180V_25C) {
171c171
<     cell (EF_SRAM_1024x32) {
---
>     cell (EF_SRAM_1024x32_wrapper) {
```

So why didn't we do that for all of the macros' corners…?

**Comment by marwaneltoukhy** [comment]
fixed with https://github.com/efabless/EF_SRAM_1024x32/pull/10
