### ISSUE TITLE
Slowest macro corner characterized at incorrect temperature

### ISSUE THREAD

**Issue by donn** [efabless/EF_SRAM_1024x32#12]
At the slowest corner, the macro is characterized at 150°C, whereas the SCLs in the sky130 PDK are characterized at 100°C (the transistor and voltage corners are correct.)

This may lead to inaccurate STA results.

**Comment by marwaneltoukhy** [comment]
@DavidRLindley Can you please add the rest of the liberty corners?

**Comment by DavidRLindley** [comment]
There are 161 total dotlib files.  Do you want them all?

**Comment by DavidRLindley** [comment]
Will do.

**Comment by DavidRLindley** [comment]
Do you want all of the dotlib files?  

_01024x032_008_18_ff_140V_100C.lib
_01024x032_008_18_ff_140V_n40C.lib
_01024x032_008_18_ff_160V_150C.lib
_01024x032_008_18_ff_165V_100C.lib
_01024x032_008_18_ff_165V_n40C.lib
_01024x032_008_18_ff_195V_100C.lib
_01024x032_008_18_ff_195V_150C.lib
_01024x032_008_18_ff_195V_n40C.lib
_01024x032_008_18_ss_135V_n40C.lib
_01024x032_008_18_ss_140V_100C.lib
_01024x032_008_18_ss_140V_n40C.lib
_01024x032_008_18_ss_160V_100C.lib
_01024x032_008_18_ss_160V_150C.lib
_01024x032_008_18_ss_160V_n40C.lib
_01024x032_008_18_tt_140V_100C.lib
_01024x032_008_18_tt_140V_25C.lib
_01024x032_008_18_tt_140V_n40C.lib
_01024x032_008_18_tt_180V_100C.lib
_01024x032_008_18_tt_180V_150C.lib
_01024x032_008_18_tt_180V_25C.lib

**Comment by marwaneltoukhy** [comment]
These are what we use
```
        "nom_tt_025C_1v80",
        "nom_ss_100C_1v60",
        "nom_ff_n40C_1v95",
        "min_tt_025C_1v80",
        "min_ss_100C_1v60",
        "min_ff_n40C_1v95",
        "max_tt_025C_1v80",
        "max_ss_100C_1v60",
        "max_ff_n40C_1v95"
```

**Comment by DavidRLindley** [comment]
I added these files.  This covers the different available corners.

EF_SRAM_1024x32_ff_140V_100C.lib
EF_SRAM_1024x32_ff_165V_100C.lib
EF_SRAM_1024x32_ff_195V_100C.lib
EF_SRAM_1024x32_ss_140V_100C.lib
EF_SRAM_1024x32_ss_160V_100C.lib
EF_SRAM_1024x32_tt_140V_100C.lib
EF_SRAM_1024x32_tt_180V_100C.lib

**Comment by marwaneltoukhy** [comment]
Thank you David!
